name: Package New Releases to .exe for macOS 14 and later

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-macos:
    name: Builds macOS release
    runs-on: macos-latest
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run PyInstaller
        run: |
          python -m PyInstaller CaTSper.spec

      - name: Package dmg
        uses: L-Super/create-dmg-actions@v1.0.3
        with:
          dmg_name: 'CaTSper-macOS-arm64'
          src_dir: 'dist/CaTSper.app'

      - name: Upload to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{github.event.release.tag_name}} CaTSper-macOS-arm64.dmg
